# Generated by Django 4.2.2 on 2023-06-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathon_api", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="registered_hackathons",
            field=models.ManyToManyField(
                related_name="registered_users", to="hackathon_api.hackathon"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
