# Generated by Django 4.0 on 2023-06-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_api', '0001_initial'),
        ('users', '0002_userprofile_registered_hackathons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registered_hackathons',
            field=models.ManyToManyField(related_name='registered_users', to='hackathon_api.Hackathon'),
        ),
    ]
