# Generated by Django 4.2.2 on 2023-06-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "background_image",
                    models.ImageField(upload_to="hackathon_backgrounds/"),
                ),
                ("hackathon_image", models.ImageField(upload_to="hackathon_images/")),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("file", "File"),
                            ("link", "Link"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("reward_prize", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
